apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend-app
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: DockerImage
      name: docker.io/fathyafi/be-app2:latest
    pushSecret:
      name: dockerhub-creds-openshft