apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.threeam.finalproject.cloud:6443
  name: api-threeam-finalproject-cloud:6443
contexts:
- context:
    cluster: api-threeam-finalproject-cloud:6443
    namespace: fathya-app
    user: developer/api-threeam-finalproject-cloud:6443
  name: fathya-app/api-threeam-finalproject-cloud:6443/developer
current-context: fathya-app/api-threeam-finalproject-cloud:6443/developer
kind: Config
preferences: {}
users:
- name: developer/api-threeam-finalproject-cloud:6443
  user:
    token: sha256~4nOspfC-A52pSzyU_ADGr6vqFxlg2Z0LTrdT2SvKn8c
