apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app1
  template:
    metadata:
      labels:
        app: backend-app1
    spec:
      containers:
      - name: backend-app1
        image: fathyafi/be-app3:latest
        ports:
          - containerPort: 8080